### ISSUE TITLE
Translations for UCUM should be moved to a CodeSystem

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#121]
https://github.com/hl7dk/dk-core/blob/20c407aa90ddb4d3ba456cd9c93ff6ca2aca44f8/input/fsh/valueSets.fsh#L225

Translations lives in CodeSystems - in this case most likely a CodeSystem fragment and supplement.

**Comment by jkiddo** [comment]
Relates to https://github.com/hl7dk/dk-core/issues/128

**Comment by Kirstinerosenbeck** [comment]
In the FHIR datatype Quantity, there is no attribute for a display-term. This is because "code" is just an attribute. Neither the Coding datatype nor the CodableConcept datatype are used. It is when these two datatypes are used, that the code is validated to match display and/or designations, and errors are cast when they do not. In Quantity, this is replaced by a string (attribute unit) without any relation to the code. As such your only option for display is to write a Danish unit here, but it cannot be given beforehand by a CodeSystem fragment and supplement - or if it has - that has no effect on the actual data. I strongly suggest that we drop this.

**Comment by jkiddo** [comment]
Then the display values should be removed from the valueset

**Comment by tmsMedcom** [comment]
@christiangasser-lakeside hvad er status på dette issue?

**Comment by christiangasser-lakeside** [comment]
@jkiddo har løst denne som en del af #128. 

(Se https://github.com/hl7dk/dk-core/blob/3.3.0/input/fsh/valueSets.fsh#L224)

Så den kan lukkes :-)
