### ISSUE TITLE
EAN identifier on Organization needs clear description

### ISSUE THREAD

**Issue by jkiddo** [hl7dk/dk-core#38]
Is the 'EAN number' in fact a GLN number - more specifically a GTIN-13 number? Should the check digit rules be added as invariant (https://www.gs1.org/services/check-digit-calculator)? Should we use the OID/Url for GLN instead as defined on https://www.hl7.org/fhir/identifier-registry.html ?

**Comment by JesperKervin** [comment]
The old term ”EAN number” is in fact today Global Location Number, GLN, as mentioned. It is not GTIN-13 number, because Global Trade Item Number is for identifying products, but both GS1 keys have a check digit based on modulus 10. 
Yes, check digit rules be added as invariant (https://www.gs1.org/services/check-digit-calculator )
OID should be: http://oid-info.com/get/1.3.88 
The list here: https://www.hl7.org/fhir/identifier-registry.html  does not contain GLN. Is that something we need to change?

**Comment by jvitrifork** [comment]
@JesperKervin - now reported on https://jira.hl7.org/browse/FHIR-34209

**Comment by jvitrifork** [comment]
See also https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Identifier.20registry

**Comment by jkiddo** [comment]
Changed to GLN in https://github.com/hl7dk/dk-core/commit/44a28e0423cb727eed99b9782db08e10e4845114
